-- =============================================================
-- SCRIPT 1: ESTRUCTURA DE BASE DE DATOS Y DATOS INICIALES
-- =============================================================

-- 1. LIMPIEZA TOTAL
----------------------------------------------------------------
DROP TABLE article_categories CASCADE CONSTRAINTS;
DROP TABLE article_tags CASCADE CONSTRAINTS;
DROP TABLE categories CASCADE CONSTRAINTS;
DROP TABLE tags CASCADE CONSTRAINTS;
DROP TABLE comments CASCADE CONSTRAINTS;
DROP TABLE articles CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;


-- 2. TABLAS
----------------------------------------------------------------
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE articles (
    article_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    title VARCHAR2(150) NOT NULL,
    art_date DATE DEFAULT SYSDATE NOT NULL,
    text CLOB NOT NULL,
    CONSTRAINT fk_articles_users FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE comments (
    comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    comment_date DATE DEFAULT SYSDATE NOT NULL,
    text VARCHAR2(500) NOT NULL,
    CONSTRAINT fk_comments_articles FOREIGN KEY (article_id) REFERENCES articles(article_id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_users FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE tags (
    tag_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE article_tags (
    article_id NUMBER NOT NULL,
    tag_id NUMBER NOT NULL,
    PRIMARY KEY (article_id, tag_id),
    CONSTRAINT fk_at_articles FOREIGN KEY (article_id) REFERENCES articles(article_id) ON DELETE CASCADE,
    CONSTRAINT fk_at_tags FOREIGN KEY (tag_id) REFERENCES tags(tag_id) ON DELETE CASCADE
);

CREATE TABLE article_categories (
    article_id NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    PRIMARY KEY (article_id, category_id),
    CONSTRAINT fk_ac_articles FOREIGN KEY (article_id) REFERENCES articles(article_id) ON DELETE CASCADE,
    CONSTRAINT fk_ac_categories FOREIGN KEY (category_id) REFERENCES categories(category_id) ON DELETE CASCADE
);


-- 3. DATOS INICIALES
----------------------------------------------------------------
-- Usuarios por defecto (ID 1 = Admin, ID 2 = Juan)
INSERT INTO users (name, email, password, role) VALUES ('Administrador Global', 'admin@blog.com', 'admin123', 'ADMIN');
INSERT INTO users (name, email, password, role) VALUES ('Juan', 'juan@blog.com', 'user123', 'USER');

-- Categorías iniciales (ID 1 = Tecnología, ID 2 = Programación)
INSERT INTO categories (name) VALUES ('Tecnología');
INSERT INTO categories (name) VALUES ('Programación');

-- Etiquetas iniciales (ID 1 = Oracle, ID 2 = Python)
INSERT INTO tags (name) VALUES ('Oracle');
INSERT INTO tags (name) VALUES ('Python');

-- Artículos iniciales
-- Artículo 1 (Escrito por el Admin)
INSERT INTO articles (user_id, title, text) 
VALUES (1, 'Introducción a Oracle y Python', 'En este primer artículo aprenderemos cómo conectar Python con bases de datos Oracle siguiendo las mejores prácticas: separando el código SQL de nuestro backend utilizando procedimientos almacenados y cursores.');

-- Artículo 2 (Escrito por Juan)
INSERT INTO articles (user_id, title, text) 
VALUES (2, 'El futuro de las bases de datos', 'La tecnología avanza rápido, pero las bases de datos relacionales siguen siendo el pilar fundamental del entorno empresarial gracias a su robustez, seguridad y capacidad de procesamiento.');

-- Vincular artículos con sus categorías
INSERT INTO article_categories (article_id, category_id) VALUES (1, 2); -- Art 1 -> Programación
INSERT INTO article_categories (article_id, category_id) VALUES (2, 1); -- Art 2 -> Tecnología

-- Vincular artículos con sus etiquetas
INSERT INTO article_tags (article_id, tag_id) VALUES (1, 1); -- Art 1 -> Oracle
INSERT INTO article_tags (article_id, tag_id) VALUES (1, 2); -- Art 1 -> Python
INSERT INTO article_tags (article_id, tag_id) VALUES (2, 1); -- Art 2 -> Oracle

-- Comentarios iniciales
-- Juan comenta el artículo del Admin
INSERT INTO comments (article_id, user_id, text) 
VALUES (1, 2, '¡Excelente artículo! Justo lo que necesitaba para estructurar correctamente mi proyecto.');

-- El Admin comenta el artículo de Juan
INSERT INTO comments (article_id, user_id, text) 
VALUES (2, 1, 'Muy buena reflexión, Juan. Es importante conocer los fundamentos. ¡Sigue así!');

COMMIT;